version: "3.3"
services:
  mongo:
    image: mongo:latest
    restart: always
    # network_mode: host
    networks:
      - traefik
  gadael:
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile
    image: repo.dalkia.online/gadael:latest
    ports:
      - "3000:3000"
    environment:
      - LOGHTTP=true
      - CSRFPROTECTION=true
      - POSTPHONE=true
      - CALLBACK_URL=https://gdtest.webinage.net
      - APP_HOST=
      - APP_PORT=3000
      - APP_COMPANY=Webinage
      - APP_LANGUAGE=fr
      - APP_CRYPTO_KEY=k8yb0brda2t
      - APP_TIMEOUT=
      - DB_INIT=true
      - DB_HOST=mongo/
      - DB_NAME=gadael
      - DB_AUTO_INDEX=true
      - LOGIN_ATTEMPT_IP=50
      - LOGIN_ATTEMPT_USER=7
      - LOGIN_ATTEMPT_LOG_EXPIRATION=20m
      - ACCOUNT_VERIFICATION=false
      - MAIL_HOST=localhost
      - MAIL_PORT=dock
      - MAIL_SECURE=
      - MAIL_USER=
      - MAIL_PASS=
      - MAIL_HEADER="Gadael email"
      - MAIL_ADDRESS=gadael@example.com
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gadael"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:gdtest.webinage.net"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.docker.network=root_traefik"
    restart: always
    depends_on: 
      - mongo
    # network_mode: host
    networks:
      - "traefik"
  traefik:
    image: traefik:latest
    command: --configFile=/traefik.toml --api --docker --docker.watch --docker.domain=localhost
    restart: always
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/traefik/traefik.toml:/traefik.toml
      - /usr/traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:test.traefik"
      - "traefik.docker.network=root_traefik"
    networks:
      - "traefik"
    
networks:
  traefik:
    # external:
    #   name: traefik_webgateway
    driver: bridge